### ISSUE TITLE
[Error] Encoder Error: Failed to initialize PCM library.

### ISSUE THREAD

**Issue by thefinalwolf** [wieslawsoltes/wavtoac3encoder#1]
Hello, I'm having an issue with both the 32 and 64 bit versions where a screen will pop up for a few milliseconds and close once **Encode** is pressed. When I check the log I see:
```
[2017-06-04, 21:19:54.140] Encoder Error: Failed to initialize PCM library.
[2017-06-04, 21:19:54.140] Error: Failed to encode all files.
```
I've tried on various virtual machines and searched around, but haven't come across a good solution. I'm hopping it's not something simple I've overlooked.

**Comment by wieslawsoltes** [comment]
@thefinalwolf Could you provide sample file and your present configuration. Seems like Aften can not read input file format.

**Comment by thefinalwolf** [comment]
In preparing the files for a response, I discovered the issue.
I was exporting 48000Hz files to WAV 32-bit float PCM vi Audacity, but the project setting was set to 41000 Hz (the default).
Setting the project to 48000 Hz before exporting solved the issue and allowed everything to work properly.
Thanks for the quick response by the way.
